### ISSUE TITLE
Question on hierarchy on class-wise level 

### ISSUE THREAD

**Issue by YiruS** [daerduoCarey/partnet_dataset#11]
Hi there,

By checking the paper and dataset, it seems that currently the hierarchy is coming from part level. Does that hierarchy hold for class-wise level? For example, in the class of lamp, we know sub-class includes street lamp, ceiling lamp, etc., which is illustrated in Figure 3 in main paper. How could we obtain this hierarchy regarding class level in the dataset?

Thanks and looking forward to your reply!
-Yiru

**Comment by Dustinpro** [comment]
It is in the dataset. Please check ./stats/after_merging_label_ids/OBJECT_CATEGORY-hier.txt

**Comment by YiruS** [comment]
> It is in the dataset. Please check ./stats/after_merging_label_ids/OBJECT_CATEGORY-hier.txt
Do you mean by the whole data called "data_v0"? It only contains subfolders with different id, where no /stats/after_merging_label_ids can be found. Could you provide more information about it?

The structure of each subfolder is like:
---meta.json
---objs/
---parts_render/
---parts_render_after_merging/
---point_sample/
---result.json
---result_after_merging.json
---tree_hier.html
---tree_hier_after_merging.html

Thanks!

**Comment by YiruS** [comment]
Do you mean by the whole data called "data_v0"? It only contains subfolders with different id, where no /stats/after_merging_label_ids can be found. Could you provide more information about it?

The structure of each subfolder is like:
---meta.json
---objs/
---parts_render/
---parts_render_after_merging/
---point_sample/
---result.json
---result_after_merging.json
---tree_hier.html
---tree_hier_after_merging.html

Thanks!

**Comment by Dustinpro** [comment]
https://github.com/daerduoCarey/partnet_dataset/blob/master/stats/after_merging_label_ids/Lamp-hier.txt

**Comment by daerduoCarey** [comment]
Thank you, @Dustinpro for wonderful replies! You are now PartNet expert!
