### ISSUE TITLE
Reassembling of parts’ models (.obj files)

### ISSUE THREAD

**Issue by SamsonYuBaiJian** [daerduoCarey/partnet_dataset#12]
Hi there, I would like to:
1) Reassemble the .obj files of the parts into their full object automatically
2) Pass the full object into Unity, while maintaining the hierarchical structure of its parts

Do you have any code that can help with any part of this process? Thank you.

**Comment by Dustinpro** [comment]
1. A simple 3d package like trimesh would help
2. Unity is not used in preparing this dataset.

**Comment by SamsonYuBaiJian** [comment]
Thanks, I tried trimesh and it helps!
