### ISSUE TITLE
Same 3D model as ShapeNet or not?

### ISSUE THREAD

**Issue by zivzone** [daerduoCarey/partnet_dataset#15]
HI,
Are the 3D models provide 2D RGB images rendered from different angles or we can render RGB image by ourselves? Are the 3D model in partnet as same as 3D model in the Shapenet? If yes, do those models have the same number? For example, a chair 3D model's number in PartNet is "xxxxxx", is this 3d model also in the ShapeNet with the same number "xxxxxx"?

**Comment by daerduoCarey** [comment]
Yes, the same models as shapenet

**Comment by bertjiazheng** [comment]
It seems that the scale of the model in the PartNet is different from the ShapeNet. Furthermore, the model in the PartNet does not contain the material and texture. So how can we render the same images with the model in PartNet?

Thanks,
Jia

**Comment by daerduoCarey** [comment]
We are trying to release PartNet with ShapeNet v3. In the meanwhile, for most of the models, PartNet is just 90-degree rotated from ShapeNet pose. After rotating them back, you can easily do scale normalization to align PartNet models to ShapeNet models. You can then write a simple chamfer-distance verification step to remove the misaligned models where we adjusted the object poses. A very small portion of data misalign.

**Comment by bertjiazheng** [comment]
Thanks for your reply. Would you mind introducing any new features with ShapeNet v3?

**Comment by zivzone** [comment]
> We are trying to release PartNet with ShapeNet v3. In the meanwhile, for most of the models, PartNet is just 90-degree rotated from ShapeNet pose. After rotating them back, you can easily do scale normalization to align PartNet models to ShapeNet models. You can then write a simple chamfer-distance verification step to remove the misaligned models where we adjusted the object poses. A very small portion of data misalign.

HI @daerduoCarey ,
Thank you for your reply！！
And same as @bertjiazheng, could I invite you to introduce any new features with ShapeNet v3?
Thanks a lot for everything!!

**Comment by bertjiazheng** [comment]
If the PartNet uses the same model with ShapeNet (i.e., including texture and material), which will benefit the community on 3D shape reconstruction from images.

**Comment by daerduoCarey** [comment]
Yes, we are pushing hard on this. Maintaining large-scale dataset such as ShapeNet and PartNet takes a lot of effort. Thank you for your patience and understanding.

We are still discussing the plan for ShapeNet v3. We will mostly fix errors regarding classification labels, pose orientations, and mesh orientations. We are also cleaning up annotation errors in the current PartNet towards a stable v1 and preparing to launch online PartNet challenges after the data clean-ups. PartNet v1 will not be released with textures/materials as some fine-grained part annotation breaks the original ShapeNet model meshes, so it would be good to consider PartNet to be a point-cloud data labeled with part labels that live in the same space with the original ShapeNet mesh model. You should render RGB images from rendering the ShapeNet models. Part masks can be rendered from PartNet released meshes which approximately delineate the part regions. We are aiming to release such data rendering with part mask information in the next PartNet v1 release.

If you have more questions or request more features, please let us know!

Best,
Kaichun

**Comment by bertjiazheng** [comment]
Thanks for your reply. Looking forward to the update.

**Comment by tengyu-liu** [comment]
Dear Kaichun, 

Is it possible for you to provide a transformation file between PartNet objs and ShapeNet objs in the future?

**Comment by daerduoCarey** [comment]
PartNet is just 90-degree rotated from ShapeNet pose. And run re-normalizaing.
This would work for most shapes.

**Comment by daerduoCarey** [comment]
please check this about the alignment to shapenet-v1: https://github.com/daerduoCarey/partnet_dataset/issues/20
