### ISSUE TITLE
Any plan to release the script used for generating the point cloud data?

### ISSUE THREAD

**Issue by Kulbear** [daerduoCarey/partnet_dataset#17]
Hi,

Thanks for the great work and the dataset. I am trying to understand how the dataset is constructed. I noticed there are point cloud data, which looks like a 10k-point data sampled from the original model from ShapeNet. I found some util functions in the repo but I cannot find a place where those functions are used. 

In this case, do you have any plan to release the script to generate the point cloud?

Best

**Comment by daerduoCarey** [comment]
There are many tools to sample point clouds from meshes, for example,

For uniform sampling, https://trimsh.org/trimesh.sample.html
For furthest-point sampling, https://github.com/sidch/Thea/tree/master/Code/Source/Tools/MeshSample

Best,
Kaichun
