### ISSUE TITLE
Problem about downloading the dataset

### ISSUE THREAD

**Issue by yolu1055** [daerduoCarey/partnet_dataset#18]
Hi,

Thank you for your great work and sharing your code and data! 

I was not able to download the PartNet from [shapenet](https://www.shapenet.org/). It seems that the website is down, so I was not able to register in. I would like to ask if there is another way to download this dataset. Thanks.

Best,

**Comment by daerduoCarey** [comment]
please ignore the certificate warning of the shapenet website.

**Comment by yolu1055** [comment]
Hi,

Thank you for your prompt reply! I really appreciate it.

It seems that the error is not caused by the certificate, and it is caused by the server. When I was trying to sign up, I got the following error:
`Exception: MongoError: Topology was destroyed`.


Best,

**Comment by daerduoCarey** [comment]
Thanks. Can you try again now?

**Comment by yolu1055** [comment]
Yes, it works. I have created my account. Thank you very much! I really appreciate your help!
