### ISSUE TITLE
Where is the training, validation and test splits of PartNet?

### ISSUE THREAD

**Issue by mtli77** [daerduoCarey/partnet_dataset#21]
Hi, @daerduoCarey 

thanks for sharing your wonderful work!
I have download the data_v0.zip of the PartNet. 
Could you please tell me that where to download the training, validation, and test splits files of PartNet?

best regards!

**Comment by daerduoCarey** [comment]
https://github.com/daerduoCarey/partnet_dataset/tree/master/stats/train_val_test_split
