### ISSUE TITLE
About the `ins_seg_h5.zip` and `sem_seg_h5.zip` data provided by the PartNet

### ISSUE THREAD

**Issue by mtli77** [daerduoCarey/partnet_dataset#22]
Hi @daerduoCarey 

I have download the `ins_seg_h5.zip` and the `sem_seg_h5.zip` data.

For `ins_seg_h5.zip`, it contains: `ins_seg_h5`, `ins_seg_h5_for_detection`, `ins_seg_h5_for_sgpn` and `ins_seg_h5_gt`. What are the differences between them, and if I want to setup my research on instance segmentation task, which data-file should I adopt?

For `sem_seg_h5.zip`, it only contains `sem_seg_h5`, I wonder which tasks about the semantic segmentation introduced in your paper ( fine-grained semantic segmentation or hierarchical semantic segmentation) does this data-file related to?

Waiting for your reply!
Best regards!

**Comment by daerduoCarey** [comment]
https://github.com/daerduoCarey/partnet_seg_exps
