### ISSUE TITLE
where can I find the original partnet 3d obj model

### ISSUE THREAD

**Issue by jeannotes** [daerduoCarey/partnet_dataset#25]
hi, I want find the original obj model, but I dind that number of  models in shapenetcore is not equal to models nums in paetnet:
eg, keyboard, in partnet ,there are 156 of keyboards, and I check keyboard name id is "03085013", and I download the zip file from "http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v2/03085013/"
actually the number is 65, so am I down the original keyboard mesh?

anything wrong?

**Comment by daerduoCarey** [comment]
yes, partnet is a subset of shapenetcore (actually, partnet also has downloaded additional models than shapenetcore). You just align shapenetcore mesh to the partnet: "We've released the transformation matrices to align ShapeNet-v1 models to the PartNet space for chairs, tables, storage furnitures and beds HERE (4x4 transformation matrix, stored as row-first). For other categories, please run THIS CODE by yourself. This alignment might fail in rare cases, but fortunately this can be detected. Check the code comments for more information. Hope this is helpful!"

**Comment by daerduoCarey** [comment]
HERE: http://download.cs.stanford.edu/orion/partnet_dataset/chair_table_storagefurniture_bed_shapenetv1_to_partnet_alignment.json
THIS CODE: http://download.cs.stanford.edu/orion/partnet_dataset/compute_transmat_shapenetv1_to_partnet.py

**Comment by jeannotes** [comment]
@daerduoCarey 
another two questions:
1. in your code, I find shapenet_cat2ids, such as :
 {
        'Chair': ['03001627'],
        'Table': ['04379243'],
        'Bed': ['02818832'],
        'StorageFurniture': ['02933112', '03337140', '02871439'],
}
can I get full shapenet cat2ids?, eg, keyboard, bag etc.

2. you mean partnet has download additional meshes, so shapenetcore is actually a subset of partnet, which means not all models from partnet can find the corresponding mesh in shaoenetcore?

**Comment by daerduoCarey** [comment]
1. https://shapenet.org/login/ refer to shapenet
2. shapenetcore and partnet has overlaps, but no one is a subset of another. yes, you are right.
