### ISSUE TITLE
Substituting handle collision STL with V-HACD generated convex STLs

### ISSUE THREAD

**Issue by JanusMaple** [daerduoCarey/partnet_dataset#27]
I am currently trying to create new cabinet and drawer model similar to the Partnet ones and facing a problem of substituting the collision mesh of drawer handles with V-HACD generated ones using Blender. I have to manually accomplish the job and I am wondering is there any automation method for that?

**Comment by daerduoCarey** [comment]
This question does not relate to the PartNet dataset. If you are asking for the urdf files for the PartNet-Mobility dataset, you can simply replace the stl file with your generated still in the urdf collision mesh list.
