### ISSUE TITLE
Alignment between ShapeNetCore v2 and PartNet point cloud

### ISSUE THREAD

**Issue by Donglin-Wang2** [daerduoCarey/partnet_dataset#29]
After downloading both the ShapeNetCore v2 and the PartNet dataset, I am having trouble figuring out how to align the ShapeNet meshes with the PartNet point cloud data. I used PyBullet to load the mesh and the point cloud. To obtain the picture below, I first found the correspondance between annotation id and ShapeNet id. I then loaded the mesh under the `"/ShapeNetCore.v2/<category_id>/<shapenet_id>/models/model_normalized.obj"` and then loaded the `"/data_v0/<anno_id>/point_sample/sample-points-all-pts-label-10000.ply"`. To produce the picture below, the <categori_id> is 03797390, the <shapenet_id> is the 7223820f07fd6b55e453535335057818, and the <anno_id> is 8745. The exact script to reproduce the picture is [here](https://github.com/Donglin-Wang2/acronym-partnet/blob/master/visualize_mesh_pointcloud.py). As seen in the picture below:
1. The scale of the point cloud is much larger.
2. The handle of the point cloud is on the top, whereas the handle of the mesh is on the bottom.
3. The origin of the point cloud is at the centre of the mug, whereas the origin of the mesh is towards the rim of the mug.

I am sure that it might be something I failed to do on my part, but I am struggling to figure out why they don't align.
![Screenshot from 2022-02-15 20-37-58](https://user-images.githubusercontent.com/71317544/154181233-b7313ae5-31b6-4edf-ae6b-9ab5f51f4d53.png)

**Comment by daerduoCarey** [comment]
please check the second item on the webpage: https://partnet.cs.stanford.edu/

NEW [Oct 25, 2020] We've released the transformation matrices to align ShapeNet-v1 models to the PartNet space for chairs, tables, storage furnitures and beds [HERE](http://download.cs.stanford.edu/orion/partnet_dataset/chair_table_storagefurniture_bed_shapenetv1_to_partnet_alignment.json) (4x4 transformation matrix, stored as row-first). For other categories, please run [THIS CODE](http://download.cs.stanford.edu/orion/partnet_dataset/compute_transmat_shapenetv1_to_partnet.py) by yourself. This alignment might fail in rare cases, but fortunately this can be detected. Check the code comments for more information. Hope this is helpful!
