### ISSUE TITLE
24 Categories 

### ISSUE THREAD

**Issue by shankargsetty** [daerduoCarey/partnet_dataset#3]
The data_v0 repository consists of folders (eg: 42) with off, pts, json, etc. But, there is no cla file provided which specifies among these folders which belong to each of the 24 categories. 
It would be great if provided.

**Comment by daerduoCarey** [comment]
Use this one to index: https://github.com/daerduoCarey/partnet_dataset/blob/master/stats/all_valid_anno_info.txt

**Comment by shankargsetty** [comment]
Thank You!
