### ISSUE TITLE
How do I properly normalize PartNet point cloud to match the ShapeNet meshes?

### ISSUE THREAD

**Issue by Donglin-Wang2** [daerduoCarey/partnet_dataset#30]
I have attempted to use the [normalize_pts()](https://github.com/daerduoCarey/partnet_dataset/blob/master/scripts/geometry_utils.py#L45) and the [normalizeOBJ](http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v2-old/shapenet/scripts/shapenetcorev2/utils.py) methods to normalize point cloud in the "sample-points-all-pts-label-10000.ply" files. Below are the results I obtained for both methods in order. I have read #19, #15, and #25 but failed to find the answer I am looking for. The closest match between the points and the mesh is in the second picture. However, there still seems to be a little bit of displacement between the points and the model. Is there a script available that matches the points almost exactly to the mesh?

I am certain that you are very busy, and I understand that maintaining a large-scale dataset is a lot of work. Therefore, I would appreciate any guidance I receive on the matter.
![Screenshot from 2022-02-21 20-23-37](https://user-images.githubusercontent.com/71317544/155046319-dcb60caf-10fb-46bb-bf40-caaea25628f5.png)
![Screenshot from 2022-02-21 20-24-11](https://user-images.githubusercontent.com/71317544/155046327-4ddc99e0-62cb-4b15-8303-5aa8365ee3b9.png)

**Comment by daerduoCarey** [comment]
please check the second item on the webpage: https://partnet.cs.stanford.edu/

NEW [Oct 25, 2020] We've released the transformation matrices to align ShapeNet-v1 models to the PartNet space for chairs, tables, storage furnitures and beds [HERE](http://download.cs.stanford.edu/orion/partnet_dataset/chair_table_storagefurniture_bed_shapenetv1_to_partnet_alignment.json) (4x4 transformation matrix, stored as row-first). For other categories, please run [THIS CODE](http://download.cs.stanford.edu/orion/partnet_dataset/compute_transmat_shapenetv1_to_partnet.py) by yourself. This alignment might fail in rare cases, but fortunately this can be detected. Check the code comments for more information. Hope this is helpful!
