### ISSUE TITLE
Unable to download 10gb chunk

### ISSUE THREAD

**Issue by abhi-vinchure** [daerduoCarey/partnet_dataset#31]
Hi,
I filled the google form and wish to download the 10gb chunk of the PartNet dataset, but it seems there is no option to do so. 
Please advise.

**Comment by daerduoCarey** [comment]
http://download.cs.stanford.edu/orion/partnet_dataset/data_v0_chunk.zip
http://download.cs.stanford.edu/orion/partnet_dataset/data_v0_chunk.z01
http://download.cs.stanford.edu/orion/partnet_dataset/data_v0_chunk.z02
...
http://download.cs.stanford.edu/orion/partnet_dataset/data_v0_chunk.z10

**Comment by abhi-vinchure** [comment]
Hi, 
I've downloaded the chunk title data_v0_chunk.z10 on my mac os laptop. However, I am running into the following issue. This also happens if I download the 300 mbs version. Am I missing any other packages needed to properly open the dataset? I have it all downloaded, but unable to access. 
<img width="456" alt="Screen Shot 2022-03-01 at 12 47 36 AM" src="https://user-images.githubusercontent.com/71155294/156135777-7425ad8d-5b93-4dca-b9ed-190f2d433638.png">
