### ISSUE TITLE
Data link not working

### ISSUE THREAD

**Issue by chenbowen** [daerduoCarey/partnet_dataset#36]
Hi! I found all data under [http://download.cs.stanford.edu/orion/partnet_dataset](https://www.google.com/url?q=http://download.cs.stanford.edu/orion/partnet_dataset/data_v0.zip&sa=D&source=editors&ust=1655964402090594&usg=AOvVaw1gO4B9JwSN7p14yfBOB6nb) are not accessible? Is the server down? 
I also checked it with some online website performance services and got the same result:
An error occurred fetching the page: HTTPS error: Connection timed out

Could you please check? Thank you!

**Comment by xiexh20** [comment]
I have the same issue, how did you solve this problem? Thanks in advance!
