### ISSUE TITLE
24 categories - no. of objects

### ISSUE THREAD

**Issue by shankargsetty** [daerduoCarey/partnet_dataset#4]
Hi,

[1] How many number of 3D objects does each of 24 classes have? 

[2] Can the visualization of ground truth of segmented objects be provided for each class as given in ShapeNet?

**Comment by daerduoCarey** [comment]
1) please read our paper
2) http://download.cs.stanford.edu/orion/partnet_dataset/data_v0/2230/tree_hier_after_merging.html

Thanks

**Comment by shankargsetty** [comment]
Thanks I got it resolved after reading your paper.

**Comment by shankargsetty** [comment]
Hi,

http://download.cs.stanford.edu/orion/partnet_dataset/data_v0/2230/tree_hier_after_merging.html
The above was for chair, how to get for other classes

**Comment by daerduoCarey** [comment]
Just simply replace the 2230 with the anno-id of non-chair models.

**Comment by shankargsetty** [comment]
Thank You.
