### ISSUE TITLE
data generation script for semantic segmentation

### ISSUE THREAD

**Issue by lodurality** [daerduoCarey/partnet_dataset#7]
Do you have semantic segmentation data generation script which generates data in folder sem_seg_h5 (similar to gen_h5_ins_seg_after_merging.py script)? 

I am currently reproducing this script and it would be nice to have ground truth.

**Comment by daerduoCarey** [comment]
It is produced directly by sampling from raw data.

**Comment by lodurality** [comment]
Thanks!
