### ISSUE TITLE
Real-world Dimensions

### ISSUE THREAD

**Issue by Dustinpro** [daerduoCarey/partnet_dataset#8]
Since there are real-world dimensions, estimates of their material composition, volume, and weight info in the ShapeNet dataset, I wonder if you have ground truth real-world dimensions for each object and other useful meta data in PartNet currently.

**Comment by daerduoCarey** [comment]
We don't have such information for PartNet. But there are some research papers that annotate some of the ShapeNet models: https://linsats.github.io/attributeTransferring/ and https://graphics.stanford.edu/projects/semgeo/
