### ISSUE TITLE
Part Renderer

### ISSUE THREAD

**Issue by Dustinpro** [daerduoCarey/partnet_dataset#9]
It is noticed that each object part in PartNet dataset is well rendered as shown in the corresponding _annoID/parts_render/_ folder. The rendering effects are very impressive. Could you please provide **codes** used for those part rendering?

**Comment by daerduoCarey** [comment]
We add some code here: https://github.com/daerduoCarey/partnet_dataset/tree/master/renderer

**Comment by Dustinpro** [comment]
Thanks!!!
